### ISSUE TITLE
e_calculator.py missing print statement

### ISSUE THREAD

**Issue by jennyyuechen** [tammytru/CodeNinjas_PythonTests#1]
While printing all of the options for the user, it is missing the change event option: 
change:
while True:
    print("1. Add new event")
    print("2. Print entire calendar")
    print("3. Delete an event")
    i = input("Choose an option: ")

to:
while True:
    print("1. Add new event")
    print("2. Print entire calendar")
    print("3. Change an event")
    print("4. Delete an event")
    i = input("Choose an option: ")

- Jenny (idk how to use github sorry ;-;)

**Comment by tammytru** [comment]
thanks for the note. I just fixed it
